[package]
name = "photography_backend"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.6"
tokio = { version = "1.48.0", features = ["full"] }
rand = "0.10.0-rc.0"
tower-http = { version = "0.6.6", features = ["full"] }


